import { Router } from 'express';
import { authenticateJWT } from '../middlewares/auth.middleware.js';
import { getProfile, updateProfile, addSocialAccount, listSocialAccounts, removeSocialAccount, updateAiKeys } from '../controllers/user.controller.js';
const router = Router();
router.get('/profile', authenticateJWT, getProfile);
router.put('/profile', authenticateJWT, updateProfile);
router.post('/social-accounts', authenticateJWT, addSocialAccount);
router.get('/social-accounts', authenticateJWT, listSocialAccounts);
router.delete('/social-accounts/:id', authenticateJWT, removeSocialAccount);
router.put('/ai-keys', authenticateJWT, updateAiKeys);
export default router;